// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Connexion directe (non poolée) : requise pour Migrate, le pooler
  // pgbouncer de Supabase (DATABASE_URL, port 6543) ne supportant pas
  // correctement le DDL nécessaire aux migrations.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
